### ISSUE TITLE
VM565 WAService.js:formatted:8030 Error: module "util/wx-axios-promise.js" is not defined

### ISSUE THREAD

**Issue by snail-boy** [hengshanMWC/wx-axios-promise#4]
VM565 WAService.js:formatted:8030 Error: module "util/wx-axios-promise.js" is not defined
报这个错是什么原因

**Comment by hengshanMWC** [comment]
检查下有没有正确导入到包？
<img width="205" alt="image" src="https://user-images.githubusercontent.com/45714422/163767129-994b68f3-c48f-466d-aa50-a400c701cf4d.png">
或者可以发个代码片段复原下
